'use client'

import { useState, useEffect } from 'react'

interface Headline { title: string; source: string; url: string; published_at: string | null }
interface Sentiment {
  stance: string; score: number; why: string; drivers: string[]
  move_24h: number; headline_count: number; generated_at: string
}

function timeAgo(iso: string | null): string {
  if (!iso) return ''
  const s = Math.max(0, Math.floor((Date.now() - new Date(iso).getTime()) / 1000))
  if (s < 3600) return `${Math.max(1, Math.floor(s / 60))}m ago`
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`
  return `${Math.floor(s / 86400)}d ago`
}

// "Why it moved" — AI-explained 24h move + the headlines behind it.
// Self-contained like MarketLpPanel: renders nothing unless the market is a recent,
// news-driven mover. Skips near-resolved markets (same guard as the homepage feed).
export default function MarketSentimentPanel(
  { marketId, dark, probability }: { marketId: string; dark: boolean; probability: number | null }
) {
  const [sent, setSent] = useState<Sentiment | null>(null)
  const [news, setNews] = useState<Headline[]>([])
  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    if (probability != null && (probability <= 0.02 || probability >= 0.98)) { setLoaded(true); return }
    let alive = true
    fetch(`/api/market-sentiment?id=${encodeURIComponent(marketId)}`)
      .then(r => (r.ok ? r.json() : null))
      .then(d => { if (alive) { setSent(d?.sentiment ?? null); setNews(d?.news ?? []); setLoaded(true) } })
      .catch(() => { if (alive) setLoaded(true) })
    return () => { alive = false }
  }, [marketId, probability])

  if (!loaded || !sent) return null

  const cardBg = dark ? '#16171a' : '#ffffff'
  const border = dark ? '#26282d' : '#eaecef'
  const txt1   = dark ? '#f5f6f8' : '#0a0b0d'
  const txt2   = dark ? '#9aa0ab' : '#5b616e'
  const txt3   = dark ? '#5b616e' : '#8a919e'
  const up     = dark ? '#2bd97c' : '#05a66b'
  const down   = dark ? '#ff6b6b' : '#e5484d'

  const moveUp = sent.move_24h > 0
  const hasDrivers = Array.isArray(sent.drivers) && sent.drivers.length > 0
  const showNews = hasDrivers && news.length > 0

  return (
    <div style={{ background: cardBg, border: `1px solid ${border}`, borderRadius: 16, padding: '20px 22px', marginBottom: 16 }}>
      {/* header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14, flexWrap: 'wrap' }}>
        <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.5px', color: '#0052ff', background: dark ? '#0f1d3d' : '#eaf0ff', borderRadius: 100, padding: '4px 10px' }}>
          AI · WHY IT MOVED
        </span>
        <span style={{ flex: 1 }} />
        <span style={{
          fontSize: 13, fontWeight: 700, color: moveUp ? up : down,
          background: moveUp ? (dark ? '#04291b' : '#e7f8f0') : (dark ? '#3a0d0d' : '#fdecec'),
          borderRadius: 8, padding: '4px 10px',
        }}>
          {moveUp ? '↑' : '↓'} {Math.abs(sent.move_24h)} pts · 24h
        </span>
      </div>

      {/* why */}
      <div style={{ fontSize: 16, fontWeight: 600, color: txt1, lineHeight: 1.45, marginBottom: hasDrivers ? 14 : 6 }}>
        {sent.why}
      </div>

      {/* drivers */}
      {hasDrivers && (
        <div style={{ display: 'flex', gap: 7, flexWrap: 'wrap', marginBottom: showNews ? 18 : 6 }}>
          {sent.drivers.slice(0, 3).map((d, i) => (
            <span key={i} style={{ fontSize: 12, fontWeight: 500, color: txt2, background: dark ? '#0d0e10' : '#f5f6f8', border: `1px solid ${border}`, borderRadius: 100, padding: '4px 11px' }}>{d}</span>
          ))}
        </div>
      )}

      {/* news list */}
      {showNews && (
        <div style={{ borderTop: `1px solid ${border}`, paddingTop: 14 }}>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.5px', color: txt3, marginBottom: 10 }}>IN THE NEWS</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 11 }}>
            {news.map((h, i) => (
              <a key={i} href={h.url} target="_blank" rel="noopener noreferrer"
                 style={{ display: 'flex', alignItems: 'baseline', gap: 9, textDecoration: 'none', color: 'inherit' }}>
                <span style={{ fontSize: 12, fontWeight: 600, color: txt2, whiteSpace: 'nowrap', flexShrink: 0 }}>{h.source}</span>
                <span style={{ flex: 1, minWidth: 0, fontSize: 13.5, color: txt1, lineHeight: 1.4 }}>{h.title}</span>
                {h.published_at && <span style={{ fontSize: 11, color: txt3, whiteSpace: 'nowrap', flexShrink: 0 }}>{timeAgo(h.published_at)}</span>}
              </a>
            ))}
          </div>
        </div>
      )}

      {/* footer */}
      <div style={{ marginTop: showNews || hasDrivers ? 16 : 10, fontSize: 11, color: txt3 }}>
        Generated by AI from recent headlines · updated {timeAgo(sent.generated_at)}. Not financial advice.
      </div>
    </div>
  )
}
